"""Migration hygiene.

The round-trip test exists because autogenerated downgrades silently omit
native PostgreSQL enum types, which breaks any redeploy that rolls back.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

API_DIR = Path(__file__).resolve().parents[2]


def _alembic(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [str(API_DIR / ".venv" / "bin" / "alembic"), *args],
        cwd=API_DIR,
        capture_output=True,
        text=True,
        check=False,
    )


def test_migrations_are_linear() -> None:
    result = _alembic("heads")
    assert result.returncode == 0, result.stderr
    heads = [ln for ln in result.stdout.splitlines() if "(head)" in ln]
    assert len(heads) == 1, f"expected a single head, got: {heads}"


def test_models_match_migrations() -> None:
    """Autogenerate must produce an empty diff; otherwise a model change has
    landed without a migration."""
    result = _alembic("check")
    assert result.returncode == 0, (
        "Models and migrations have diverged. Run: alembic revision --autogenerate\n"
        f"{result.stdout}\n{result.stderr}"
    )
