"""Notifications: the in-app inbox, and the email/SMS outbox behind it.

Callers describe WHAT happened with a Message; this module decides who gets it
on which channel. Notifications are written in the caller's transaction, and
delivery is queued only after that transaction commits.

Channel policy:
  * in-app    -- always
  * email     -- every message, when SMTP is configured and the user has an email
  * SMS       -- only messages that carry `sms` text (money and leave decisions),
                 when an SMS provider is configured and the user has a valid
                 Nepali mobile number. SMS costs money per message.

Every figure in a message (amounts, dates) comes from the database. Nothing
here is generated by a model -- see docs/adr/0003.
"""

from __future__ import annotations

import re
import uuid
from collections.abc import Iterable
from dataclasses import dataclass
from datetime import date
from decimal import Decimal

from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import get_settings
from app.core.logging import get_logger
from app.models.enums import (
    ComplaintStatus,
    LeaveStatus,
    NotificationCategory,
    NotificationChannel,
    PaymentMethod,
    UserRole,
)
from app.models.notification import Notification, NotificationDelivery
from app.models.user import Student, User
from app.workers.enqueue import enqueue_after_commit

log = get_logger("services.notifications")

DISPATCH_TASK = "notifications.dispatch"
APPROVER_ROLES = (UserRole.WARDEN, UserRole.SUPER_ADMIN)

_NEPAL_MOBILE = re.compile(r"^9[678]\d{8}$")


@dataclass(frozen=True, slots=True)
class Message:
    category: NotificationCategory
    title: str
    body: str
    link: str | None = None
    # Only messages that justify the cost of an SMS carry SMS text.
    sms: str | None = None


def normalise_nepal_mobile(raw: str | None) -> str | None:
    """Return a 10-digit Nepali mobile number, or None if `raw` is not one.

    Accepts the forms people actually type: '98XXXXXXXX', '+977-98XXXXXXXX',
    '977 98XX XXX XXX'. Landlines and foreign numbers are not SMS-able here.
    """
    if not raw:
        return None
    digits = re.sub(r"\D", "", raw)
    if len(digits) == 13 and digits.startswith("977"):
        digits = digits[3:]
    return digits if _NEPAL_MOBILE.match(digits) else None


def compose_email_text(message: Message) -> str:
    lines = [message.body]
    if message.link:
        base = get_settings().web_base_url.rstrip("/")
        lines += ["", f"Open the hostel portal: {base}{message.link}"]
    lines += [
        "",
        "-- ",
        "Kutumba 1 Girls Hostel, Pokhara",
        "This is an automated message. Please do not reply to it.",
    ]
    return "\n".join(lines)


class NotificationService:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def notify(
        self,
        user_ids: Iterable[uuid.UUID],
        message: Message,
        *,
        dedupe_key: str | None = None,
    ) -> int:
        """Record `message` for each active user and queue its deliveries.

        With a `dedupe_key`, a user who already has that notification is
        skipped, which is what makes scheduled jobs safe to re-run. Returns the
        number of notifications created.
        """
        ids = list(dict.fromkeys(user_ids))
        if not ids:
            return 0

        settings = get_settings().notify
        users = (
            await self._session.execute(
                select(User.id, User.email, User.phone).where(
                    User.id.in_(ids), User.is_active.is_(True)
                )
            )
        ).all()

        created = 0
        outbox = False
        for user_id, email, phone in users:
            stmt = pg_insert(Notification).values(
                id=uuid.uuid4(),
                user_id=user_id,
                category=message.category,
                title=message.title[:200],
                body=message.body,
                link=message.link,
                dedupe_key=dedupe_key,
            )
            if dedupe_key is not None:
                stmt = stmt.on_conflict_do_nothing(
                    index_elements=["user_id", "dedupe_key"],
                    index_where=Notification.dedupe_key.is_not(None),
                )
            notification_id = (
                await self._session.execute(stmt.returning(Notification.id))
            ).scalar_one_or_none()
            if notification_id is None:
                continue  # this user was already notified about this
            created += 1

            if settings.email_enabled and email:
                self._session.add(
                    NotificationDelivery(
                        notification_id=notification_id,
                        channel=NotificationChannel.EMAIL,
                        destination=email,
                        content=compose_email_text(message),
                    )
                )
                outbox = True
            if settings.sms_enabled and message.sms:
                number = normalise_nepal_mobile(phone)
                if number is None:
                    if phone:
                        log.info("sms_skipped_unusable_number", user_id=str(user_id))
                else:
                    self._session.add(
                        NotificationDelivery(
                            notification_id=notification_id,
                            channel=NotificationChannel.SMS,
                            destination=number,
                            content=message.sms,
                        )
                    )
                    outbox = True

        if outbox:
            await self._session.flush()
            enqueue_after_commit(self._session, DISPATCH_TASK)
        return created

    async def notify_roles(
        self,
        roles: Iterable[UserRole],
        message: Message,
        *,
        exclude: uuid.UUID | None = None,
        dedupe_key: str | None = None,
    ) -> int:
        ids = (
            (
                await self._session.execute(
                    select(User.id).where(User.role.in_(list(roles)), User.is_active.is_(True))
                )
            )
            .scalars()
            .all()
        )
        return await self.notify([i for i in ids if i != exclude], message, dedupe_key=dedupe_key)

    async def notify_student(
        self, student_id: uuid.UUID, message: Message, *, dedupe_key: str | None = None
    ) -> int:
        user_id = (
            await self._session.execute(select(Student.user_id).where(Student.id == student_id))
        ).scalar_one_or_none()
        if user_id is None:
            return 0
        return await self.notify([user_id], message, dedupe_key=dedupe_key)


# ---------------------------------------------------------------- messages


def _npr(amount: Decimal) -> str:
    return f"NPR {amount:,.2f}"


def _day(d: date) -> str:
    return f"{d:%d %b %Y}"


def _words(value: str) -> str:
    return value.replace("_", " ").lower()


def _excerpt(text: str, limit: int = 140) -> str:
    text = " ".join(text.split())
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def announcement_message(title: str, body: str) -> Message:
    return Message(
        NotificationCategory.ANNOUNCEMENT,
        title=f"Notice: {title}",
        body=body,
        link="/dashboard",
    )


def leave_requested_message(
    *,
    student_name: str,
    student_code: str,
    leave_type: str,
    from_date: date,
    to_date: date,
    reason: str,
) -> Message:
    return Message(
        NotificationCategory.LEAVE_REQUESTED,
        title=f"Leave request from {student_name}",
        body=(
            f"{student_name} ({student_code}) has requested {_words(leave_type)} leave "
            f"from {_day(from_date)} to {_day(to_date)}.\n\nReason: {_excerpt(reason, 400)}"
        ),
        link="/leave",
    )


def leave_decided_message(
    *, status: LeaveStatus, leave_type: str, from_date: date, to_date: date, note: str | None
) -> Message:
    verdict = "approved" if status is LeaveStatus.APPROVED else "rejected"
    body = (
        f"Your {_words(leave_type)} leave from {_day(from_date)} to {_day(to_date)} "
        f"has been {verdict}."
    )
    if note:
        body += f"\n\nNote from the warden: {note}"
    return Message(
        NotificationCategory.LEAVE_DECIDED,
        title=f"Leave {verdict}",
        body=body,
        link="/leave",
        sms=(
            f"Kutumba Hostel: your leave from {_day(from_date)} to {_day(to_date)} "
            f"has been {verdict}."
        ),
    )


def complaint_updated_message(*, status: ComplaintStatus, excerpt_source: str) -> Message:
    label = _words(status.value)
    return Message(
        NotificationCategory.COMPLAINT_UPDATED,
        title=f"Complaint {label}",
        body=f'Your complaint is now {label}.\n\n"{_excerpt(excerpt_source)}"',
        link="/complaints",
    )


def invoice_issued_message(
    *, invoice_number: str, total: Decimal, due_date: date, period_start: date, period_end: date
) -> Message:
    return Message(
        NotificationCategory.INVOICE_ISSUED,
        title=f"New invoice {invoice_number}",
        body=(
            f"Invoice {invoice_number} for {_day(period_start)} to {_day(period_end)} "
            f"has been issued: {_npr(total)}, due by {_day(due_date)}."
        ),
        link="/fees",
    )


def fee_reminder_message(*, invoice_number: str, amount_due: Decimal, due_date: date) -> Message:
    return Message(
        NotificationCategory.FEE_REMINDER,
        title=f"Fee due on {_day(due_date)}",
        body=(
            f"A reminder that {_npr(amount_due)} on invoice {invoice_number} "
            f"is due by {_day(due_date)}."
        ),
        link="/fees",
        sms=(
            f"Kutumba Hostel: {_npr(amount_due)} (invoice {invoice_number}) "
            f"is due by {_day(due_date)}."
        ),
    )


def fee_overdue_message(*, invoice_number: str, amount_due: Decimal, due_date: date) -> Message:
    return Message(
        NotificationCategory.FEE_OVERDUE,
        title=f"Invoice {invoice_number} is overdue",
        body=(
            f"Invoice {invoice_number} was due on {_day(due_date)} and "
            f"{_npr(amount_due)} is still outstanding. Please pay at the hostel office "
            "or contact the warden."
        ),
        link="/fees",
        sms=(
            f"Kutumba Hostel: invoice {invoice_number} is overdue. "
            f"{_npr(amount_due)} outstanding since {_day(due_date)}."
        ),
    )


PAYMENT_METHOD_LABELS = {
    PaymentMethod.CASH: "cash",
    PaymentMethod.BANK_TRANSFER: "bank transfer",
    PaymentMethod.ESEWA: "eSewa",
    PaymentMethod.KHALTI: "Khalti",
    PaymentMethod.CHEQUE: "cheque",
}


def payment_method_label(method: PaymentMethod) -> str:
    return PAYMENT_METHOD_LABELS.get(method, _words(method.value))


def payment_received_message(
    *, amount: Decimal, method: PaymentMethod, invoice_number: str | None
) -> Message:
    towards = f" towards invoice {invoice_number}" if invoice_number else ""
    return Message(
        NotificationCategory.PAYMENT_RECEIVED,
        title=f"Payment received: {_npr(amount)}",
        body=(
            f"We have recorded your {payment_method_label(method)} payment "
            f"of {_npr(amount)}{towards}."
        ),
        link="/fees",
    )


def room_allocated_message(
    *, block_name: str, room_number: str, bed_label: str, from_date: date
) -> Message:
    return Message(
        NotificationCategory.ROOM_ALLOCATED,
        title=f"Room {room_number} allocated",
        body=(
            f"You have been allocated {block_name}, room {room_number}, bed {bed_label}, "
            f"from {_day(from_date)}."
        ),
        link="/dashboard",
    )


def password_changed_message(*, by_staff: bool) -> Message:
    who = "by the hostel office" if by_staff else "from your account"
    return Message(
        NotificationCategory.ACCOUNT_SECURITY,
        title="Your password was changed",
        body=(
            f"The password for your hostel portal account was changed {who}. "
            "If you did not expect this, contact the warden immediately."
        ),
        link="/dashboard",
    )
