"""initial schema

Revision ID: be8e8657aa36
Revises: 0001_extensions
Create Date: 2026-09-19 01:14:43.320352
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '0002_initial_schema'
down_revision: str | None = '0001_extensions'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('floors > 0', name='ck_blocks_floors_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fee_structures',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount_npr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cadence', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_npr >= 0', name='ck_fee_amount_nonneg'),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_fee_effective_order'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mess_menus',
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'SNACKS', 'DINNER', name='meal_type'), nullable=False),
    sa.Column('items', sa.Text(), nullable=False),
    sa.Column('serving_time', sa.String(length=40), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='ck_menu_dow_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_of_week', 'meal_type', name='uq_menu_day_meal')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'WARDEN', 'STAFF', 'STUDENT', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_table('ai_operations',
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'SKIPPED', name='ai_operation_status'), nullable=False),
    sa.Column('error_category', sa.Enum('TIMEOUT', 'RATE_LIMITED', 'UNAVAILABLE', 'SCHEMA_INVALID', 'SAFETY_BLOCKED', 'AUTH', 'BAD_REQUEST', 'UNKNOWN', name='ai_error_category'), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_operations_operation'), 'ai_operations', ['operation'], unique=False)
    op.create_index(op.f('ix_ai_operations_request_id'), 'ai_operations', ['request_id'], unique=False)
    op.create_index(op.f('ix_ai_operations_user_id'), 'ai_operations', ['user_id'], unique=False)
    op.create_index('ix_ai_ops_created', 'ai_operations', ['created_at'], unique=False)
    op.create_index('ix_ai_ops_operation_status', 'ai_operations', ['operation', 'status'], unique=False)
    op.create_table('announcements',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_announcements_window', 'announcements', ['publish_at', 'expires_at'], unique=False)
    op.create_table('assistant_conversations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_conversations_user_id'), 'assistant_conversations', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('documents',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_uri', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('doc_type', sa.Enum('HOSTEL_RULES', 'FEE_POLICY', 'LEAVE_POLICY', 'MESS_POLICY', 'NOTICE', 'FAQ', 'OTHER', name='document_type'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'INDEXED', 'FAILED', 'ARCHIVED', name='document_status'), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=True)
    op.create_index('ix_documents_type_status', 'documents', ['doc_type', 'status'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_jti', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('rooms',
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.Enum('SINGLE', 'DOUBLE', 'TRIPLE', 'DORMITORY', name='room_type'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'FULL', 'MAINTENANCE', 'CLOSED', name='room_status'), nullable=False),
    sa.Column('monthly_rate_npr', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity > 0 AND capacity <= 12', name='ck_rooms_capacity_range'),
    sa.CheckConstraint('floor >= 0', name='ck_rooms_floor_nonneg'),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'room_number', name='uq_room_number_per_block')
    )
    op.create_index('ix_rooms_status', 'rooms', ['status'], unique=False)
    op.create_table('students',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('student_code', sa.String(length=32), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('college', sa.String(length=160), nullable=True),
    sa.Column('program', sa.String(length=160), nullable=True),
    sa.Column('guardian_name', sa.String(length=160), nullable=True),
    sa.Column('guardian_phone', sa.String(length=32), nullable=True),
    sa.Column('guardian_relation', sa.String(length=64), nullable=True),
    sa.Column('emergency_contact', sa.String(length=32), nullable=True),
    sa.Column('permanent_address', sa.Text(), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PROSPECTIVE', 'ACTIVE', 'ON_LEAVE', 'ALUMNI', 'SUSPENDED', name='student_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_students_status', 'students', ['status'], unique=False)
    op.create_index(op.f('ix_students_student_code'), 'students', ['student_code'], unique=True)
    op.create_table('assistant_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'TOOL', 'SYSTEM', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_operation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ai_operation_id'], ['ai_operations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['assistant_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_messages_conversation_id'), 'assistant_messages', ['conversation_id'], unique=False)
    op.create_table('beds',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('bed_label', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('VACANT', 'OCCUPIED', 'RESERVED', 'OUT_OF_SERVICE', name='bed_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'bed_label', name='uq_bed_label_per_room')
    )
    op.create_index('ix_beds_status', 'beds', ['status'], unique=False)
    op.create_table('complaints',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'TRIAGED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REJECTED', name='complaint_status'), nullable=False),
    sa.Column('category', sa.Enum('WATER', 'ELECTRICITY', 'INTERNET', 'CLEANLINESS', 'FOOD', 'MAINTENANCE', 'SECURITY', 'NOISE', 'HARASSMENT', 'STAFF_BEHAVIOUR', 'OTHER', name='complaint_category'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='complaint_priority'), nullable=True),
    sa.Column('department', sa.Enum('MAINTENANCE', 'HOUSEKEEPING', 'MESS', 'SECURITY', 'IT', 'ADMINISTRATION', 'WARDEN_OFFICE', name='department'), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('overridden_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_complaints_created', 'complaints', ['created_at'], unique=False)
    op.create_index('ix_complaints_status_priority', 'complaints', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_complaints_student_id'), 'complaints', ['student_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_path', sa.String(length=300), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', text)", persisted=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunk_index_per_document')
    )
    op.create_index('ix_chunks_tsv', 'document_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_chunks_content_hash'), 'document_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('fee_invoices',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'VOID', name='invoice_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('period_end >= period_start', name='ck_invoice_period_order'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_fee_invoices_student_id'), 'fee_invoices', ['student_id'], unique=False)
    op.create_index('ix_invoices_due', 'fee_invoices', ['due_date'], unique=False)
    op.create_index('ix_invoices_student_status', 'fee_invoices', ['student_id', 'status'], unique=False)
    op.create_table('leave_requests',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.Enum('HOME_VISIT', 'MEDICAL', 'ACADEMIC', 'EMERGENCY', 'OTHER', name='leave_type'), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED', name='leave_status'), nullable=False),
    sa.Column('guardian_consent', sa.Boolean(), nullable=False),
    sa.Column('approver_user_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leave_dates', 'leave_requests', ['from_date', 'to_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_student_id'), 'leave_requests', ['student_id'], unique=False)
    op.create_index('ix_leave_student_status', 'leave_requests', ['student_id', 'status'], unique=False)
    op.create_table('mess_feedback',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('meal_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'SNACKS', 'DINNER', name='meal_type'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_feedback_rating_range'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'meal_date', 'meal_type', name='uq_feedback_per_meal')
    )
    op.create_index('ix_feedback_date_meal', 'mess_feedback', ['meal_date', 'meal_type'], unique=False)
    op.create_index(op.f('ix_mess_feedback_student_id'), 'mess_feedback', ['student_id'], unique=False)
    op.create_table('rag_queries',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('retrieved_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dense_hits', sa.Integer(), nullable=True),
    sa.Column('lexical_hits', sa.Integer(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('grounded', sa.Boolean(), nullable=True),
    sa.Column('retrieval_ms', sa.Integer(), nullable=True),
    sa.Column('generation_ms', sa.Integer(), nullable=True),
    sa.Column('ai_operation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ai_operation_id'], ['ai_operations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_queries_user_id'), 'rag_queries', ['user_id'], unique=False)
    op.create_table('bed_assignments',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('bed_id', sa.UUID(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', 'CANCELLED', name='assignment_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('to_date IS NULL OR to_date >= from_date', name='ck_assignment_date_order'),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignments_student', 'bed_assignments', ['student_id', 'status'], unique=False)
    op.create_index('uq_one_active_bed_per_student', 'bed_assignments', ['student_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_index('uq_one_active_occupant_per_bed', 'bed_assignments', ['bed_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('chunk_embeddings',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'model', name='uq_embedding_per_chunk_model')
    )
    op.create_table('complaint_ai_analyses',
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'SKIPPED', name='ai_operation_status'), nullable=False),
    sa.Column('error_category', sa.Enum('TIMEOUT', 'RATE_LIMITED', 'UNAVAILABLE', 'SCHEMA_INVALID', 'SAFETY_BLOCKED', 'AUTH', 'BAD_REQUEST', 'UNKNOWN', name='ai_error_category'), nullable=True),
    sa.Column('category', sa.Enum('WATER', 'ELECTRICITY', 'INTERNET', 'CLEANLINESS', 'FOOD', 'MAINTENANCE', 'SECURITY', 'NOISE', 'HARASSMENT', 'STAFF_BEHAVIOUR', 'OTHER', name='complaint_category'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='complaint_priority'), nullable=True),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', 'MIXED', name='sentiment'), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('suggested_department', sa.Enum('MAINTENANCE', 'HOUSEKEEPING', 'MESS', 'SECURITY', 'IT', 'ADMINISTRATION', 'WARDEN_OFFICE', name='department'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyses_model_version', 'complaint_ai_analyses', ['model', 'prompt_version'], unique=False)
    op.create_index(op.f('ix_complaint_ai_analyses_complaint_id'), 'complaint_ai_analyses', ['complaint_id'], unique=False)
    op.create_table('complaint_events',
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('from_status', sa.Enum('SUBMITTED', 'TRIAGED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REJECTED', name='complaint_status'), nullable=True),
    sa.Column('to_status', sa.Enum('SUBMITTED', 'TRIAGED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REJECTED', name='complaint_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_events_complaint_id'), 'complaint_events', ['complaint_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_amount_npr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_line_qty_positive'),
    sa.ForeignKeyConstraint(['invoice_id'], ['fee_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_documents',
    sa.Column('leave_request_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_uri', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['leave_request_id'], ['leave_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mess_feedback_ai',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'SKIPPED', name='ai_operation_status'), nullable=False),
    sa.Column('error_category', sa.Enum('TIMEOUT', 'RATE_LIMITED', 'UNAVAILABLE', 'SCHEMA_INVALID', 'SAFETY_BLOCKED', 'AUTH', 'BAD_REQUEST', 'UNKNOWN', name='ai_error_category'), nullable=True),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', 'MIXED', name='sentiment'), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['mess_feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_id')
    )
    op.create_table('payments',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('amount_npr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'BANK_TRANSFER', 'ESEWA', 'KHALTI', 'CHEQUE', name='payment_method'), nullable=False),
    sa.Column('reference_no', sa.String(length=120), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_by_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('RECORDED', 'REVERSED', name='payment_status'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_npr > 0', name='ck_payment_amount_positive'),
    sa.ForeignKeyConstraint(['invoice_id'], ['fee_invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_payments_paid_at', 'payments', ['paid_at'], unique=False)
    op.create_index(op.f('ix_payments_student_id'), 'payments', ['student_id'], unique=False)
    op.create_table('student_ledger_entries',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('DEBIT', 'CREDIT', name='ledger_entry_type'), nullable=False),
    sa.Column('amount_npr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount_npr > 0', name='ck_ledger_amount_positive'),
    sa.ForeignKeyConstraint(['invoice_id'], ['fee_invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_student_time', 'student_ledger_entries', ['student_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_student_ledger_entries_student_id'), 'student_ledger_entries', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_ledger_entries_student_id'), table_name='student_ledger_entries')
    op.drop_index('ix_ledger_student_time', table_name='student_ledger_entries')
    op.drop_table('student_ledger_entries')
    op.drop_index(op.f('ix_payments_student_id'), table_name='payments')
    op.drop_index('ix_payments_paid_at', table_name='payments')
    op.drop_table('payments')
    op.drop_table('mess_feedback_ai')
    op.drop_table('leave_documents')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_complaint_events_complaint_id'), table_name='complaint_events')
    op.drop_table('complaint_events')
    op.drop_index(op.f('ix_complaint_ai_analyses_complaint_id'), table_name='complaint_ai_analyses')
    op.drop_index('ix_analyses_model_version', table_name='complaint_ai_analyses')
    op.drop_table('complaint_ai_analyses')
    op.drop_table('chunk_embeddings')
    op.drop_index('uq_one_active_occupant_per_bed', table_name='bed_assignments', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('uq_one_active_bed_per_student', table_name='bed_assignments', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('ix_assignments_student', table_name='bed_assignments')
    op.drop_table('bed_assignments')
    op.drop_index(op.f('ix_rag_queries_user_id'), table_name='rag_queries')
    op.drop_table('rag_queries')
    op.drop_index(op.f('ix_mess_feedback_student_id'), table_name='mess_feedback')
    op.drop_index('ix_feedback_date_meal', table_name='mess_feedback')
    op.drop_table('mess_feedback')
    op.drop_index('ix_leave_student_status', table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_student_id'), table_name='leave_requests')
    op.drop_index('ix_leave_dates', table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index('ix_invoices_student_status', table_name='fee_invoices')
    op.drop_index('ix_invoices_due', table_name='fee_invoices')
    op.drop_index(op.f('ix_fee_invoices_student_id'), table_name='fee_invoices')
    op.drop_table('fee_invoices')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_content_hash'), table_name='document_chunks')
    op.drop_index('ix_chunks_tsv', table_name='document_chunks', postgresql_using='gin')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_complaints_student_id'), table_name='complaints')
    op.drop_index('ix_complaints_status_priority', table_name='complaints')
    op.drop_index('ix_complaints_created', table_name='complaints')
    op.drop_table('complaints')
    op.drop_index('ix_beds_status', table_name='beds')
    op.drop_table('beds')
    op.drop_index(op.f('ix_assistant_messages_conversation_id'), table_name='assistant_messages')
    op.drop_table('assistant_messages')
    op.drop_index(op.f('ix_students_student_code'), table_name='students')
    op.drop_index('ix_students_status', table_name='students')
    op.drop_table('students')
    op.drop_index('ix_rooms_status', table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_documents_type_status', table_name='documents')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_index('ix_audit_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assistant_conversations_user_id'), table_name='assistant_conversations')
    op.drop_table('assistant_conversations')
    op.drop_index('ix_announcements_window', table_name='announcements')
    op.drop_table('announcements')
    op.drop_index('ix_ai_ops_operation_status', table_name='ai_operations')
    op.drop_index('ix_ai_ops_created', table_name='ai_operations')
    op.drop_index(op.f('ix_ai_operations_user_id'), table_name='ai_operations')
    op.drop_index(op.f('ix_ai_operations_request_id'), table_name='ai_operations')
    op.drop_index(op.f('ix_ai_operations_operation'), table_name='ai_operations')
    op.drop_table('ai_operations')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('mess_menus')
    op.drop_table('fee_structures')
    op.drop_table('blocks')
    # ### end Alembic commands ###

    # Native PostgreSQL enum types are NOT dropped by op.drop_table(): they are
    # standalone objects. Without this, a downgrade followed by an upgrade fails
    # with "type ... already exists". Several types are shared by more than one
    # table, so they are dropped once here, after every table is gone.
    op.execute("DROP TYPE IF EXISTS ai_error_category")
    op.execute("DROP TYPE IF EXISTS ai_operation_status")
    op.execute("DROP TYPE IF EXISTS assignment_status")
    op.execute("DROP TYPE IF EXISTS bed_status")
    op.execute("DROP TYPE IF EXISTS complaint_category")
    op.execute("DROP TYPE IF EXISTS complaint_priority")
    op.execute("DROP TYPE IF EXISTS complaint_status")
    op.execute("DROP TYPE IF EXISTS department")
    op.execute("DROP TYPE IF EXISTS document_status")
    op.execute("DROP TYPE IF EXISTS document_type")
    op.execute("DROP TYPE IF EXISTS invoice_status")
    op.execute("DROP TYPE IF EXISTS leave_status")
    op.execute("DROP TYPE IF EXISTS leave_type")
    op.execute("DROP TYPE IF EXISTS ledger_entry_type")
    op.execute("DROP TYPE IF EXISTS meal_type")
    op.execute("DROP TYPE IF EXISTS message_role")
    op.execute("DROP TYPE IF EXISTS payment_method")
    op.execute("DROP TYPE IF EXISTS payment_status")
    op.execute("DROP TYPE IF EXISTS room_status")
    op.execute("DROP TYPE IF EXISTS room_type")
    op.execute("DROP TYPE IF EXISTS sentiment")
    op.execute("DROP TYPE IF EXISTS student_status")
    op.execute("DROP TYPE IF EXISTS user_role")
