"""notifications outbox, monthly billing, invoice number sequence

Revision ID: 0004_notifications_billing
Revises: 0003_vector_index
Create Date: 2026-09-23 23:25:07.365460
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0004_notifications_billing'
down_revision: str | None = '0003_vector_index'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('ANNOUNCEMENT', 'LEAVE_REQUESTED', 'LEAVE_DECIDED', 'COMPLAINT_UPDATED', 'INVOICE_ISSUED', 'FEE_REMINDER', 'FEE_OVERDUE', 'PAYMENT_RECEIVED', 'ROOM_ALLOCATED', 'ACCOUNT_SECURITY', name='notification_category'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id'], unique=False, postgresql_where=sa.text('read_at IS NULL'))
    op.create_index('uq_notifications_user_dedupe', 'notifications', ['user_id', 'dedupe_key'], unique=True, postgresql_where=sa.text('dedupe_key IS NOT NULL'))
    op.create_table('notification_deliveries',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', name='notification_channel'), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENDING', 'SENT', 'FAILED', name='delivery_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts >= 0', name='ck_delivery_attempts_nonneg'),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deliveries_due', 'notification_deliveries', ['status', 'next_attempt_at'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_notification_id'), 'notification_deliveries', ['notification_id'], unique=False)
    op.add_column('announcements', sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fee_invoices', sa.Column('billing_period', sa.String(length=7), nullable=True))
    op.create_index('uq_invoice_billing_period_per_student', 'fee_invoices', ['student_id', 'billing_period'], unique=True, postgresql_where=sa.text("billing_period IS NOT NULL AND status <> 'VOID'"))
    # ### end Alembic commands ###

    # Autogenerate does not detect CHECK constraints added to existing tables.
    op.create_check_constraint(
        'ck_invoice_billing_period_format',
        'fee_invoices',
        "billing_period IS NULL OR billing_period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'",
    )

    # Invoice numbers come from a sequence. The previous count(*)+1 scheme could
    # hand two concurrent requests the same number. The sequence continues after
    # the highest number already issued, so existing numbers are never reused.
    op.execute("CREATE SEQUENCE invoice_number_seq")
    op.execute(
        "SELECT setval('invoice_number_seq', COALESCE(("
        "SELECT MAX(CAST(split_part(invoice_number, '-', 3) AS integer)) FROM fee_invoices "
        "WHERE invoice_number ~ '^INV-[0-9]{6}-[0-9]+$'), 0) + 1, false)"
    )


def downgrade() -> None:
    op.execute("DROP SEQUENCE IF EXISTS invoice_number_seq")
    op.drop_constraint('ck_invoice_billing_period_format', 'fee_invoices', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_invoice_billing_period_per_student', table_name='fee_invoices', postgresql_where=sa.text("billing_period IS NOT NULL AND status <> 'VOID'"))
    op.drop_column('fee_invoices', 'billing_period')
    op.drop_column('announcements', 'notified_at')
    op.drop_index(op.f('ix_notification_deliveries_notification_id'), table_name='notification_deliveries')
    op.drop_index('ix_deliveries_due', table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index('uq_notifications_user_dedupe', table_name='notifications', postgresql_where=sa.text('dedupe_key IS NOT NULL'))
    op.drop_index('ix_notifications_user_unread', table_name='notifications', postgresql_where=sa.text('read_at IS NULL'))
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###

    # Autogenerated downgrades omit native enum types; leaving them behind
    # breaks the next upgrade.
    op.execute("DROP TYPE IF EXISTS delivery_status")
    op.execute("DROP TYPE IF EXISTS notification_channel")
    op.execute("DROP TYPE IF EXISTS notification_category")
